version: '3.7'
services:
  phoenix:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: /bin/sh -c "mix do ecto.create, ecto.migrate; mix phx.server"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?ssl=false
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      COIN: KAVA
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_HTTP_URL: https://evm.evm-internal.kava.io:443
      ETHEREUM_JSONRPC_WS_URL: ws://evm-ws.evm-internal.kava.io:443
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
